version: '3.8'

services:
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: 4dm1m15tr4t0r
      MYSQL_DATABASE: agendadb
      MYSQL_USER: agendauser
      MYSQL_PASSWORD: adm1n1str4t0r
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    build:
      context: ./
    command: gunicorn --bind 0.0.0.0:8000 gruposalinas.wsgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=False
      - DB_ENGINE=django.db.backends.mysql
      - DB_NAME=agendadb
      - DB_USER=agendauser
      - DB_PASSWORD=adm1n1str4t0r
      - DB_HOST=db
      - DB_PORT=3306
      - DJANGO_SETTINGS_MODULE=gruposalinas.settings

volumes:
  db_data:
