# Generated by Django 5.1 on 2024-08-28 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarioagendas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Telefonos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10)),
                ('usuarioagenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numeros', to='usuarioagendas.usuariosistema')),
            ],
        ),
    ]
