# Generated by Django 5.1 on 2024-08-29 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarioagendas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariosistema',
            name='password',
        ),
    ]
